### ISSUE TITLE
Compilation in Windows

### ISSUE THREAD

**Issue by ANG0-0GNA** [ohirose/bcpd#13]
Hi, Professor Hirose,

I want to compile this project in windows. I use Qt with MinGW 32-bit to build this project. I download the lapack&blas precompiled binaries for Win32. The project can be compiled with no error. But when I replace the 'bcpd.exe' file and run the demo in Matlab, it doesn't work. Could you give me some suggestions to do this work?

Best regards,
Ang

**Comment by ohirose** [comment]
Hi, Ang

Thank you for your interest in BCPD!  Please paste the error message you encountered.
Also, please execute bcpd.exe from the DOS prompt; if you observed an error message,
please let me know it.

Regards,
Osamu

**Comment by ANG0-0GNA** [comment]
It works after add dll file following the error message.
I execute bcpd.exe from the DOS prompt. There are some error messages like 'libmmd.dll was not found'. I download three dll files (libmmd.dll, libifcoremdd.dll, msvcr120d.dll) and put them into the bcpd.exe directory. Then it works.
Thank you very much for your help!

bests,
Ang
