### ISSUE TITLE
Performance on registering partially overlapped point clouds

### ISSUE THREAD

**Issue by szx0112** [ohirose/bcpd#17]
Thanks for sharing the code. I run the code with the provided dataset and the performance is great.

I am wondering if the algorithm works when the source point cloud only covers a partial of the target or vice verse. For example, the two point clouds are only 70% overlapping. This condition fits many real-world applications.

If it is still working, what are the parameters need to be tuned for the best performance? Thanks.

**Comment by ohirose** [comment]
Please try demo codes in `bcpd/demo/bcpd-rigid` if you are mentioning rigid registration.
In the case of non-rigid registration, attaching the option `-ux -g0.1` might work better if input partial point clouds are roughly registered using rigid registration. Thanks.

**Comment by szx0112** [comment]
@ohirose Thanks for the reply.

I am trying to register the point clouds of a tube from two scans. The second scan is drifted (using camera) and result in a distorted model. I use the ICP but find the rigid transformation is insufficient to obtain accurate registration. Then I use the BCPD (follow codes in ShapeTransfer*.sh) to refine the ICP result. However, I found there is only a minor improvement in the final result. There are still mis-alignment between the two point clouds. Is there something wrong with my parameter setup (please see below)? Or BCPD is not designed to handle such problem? Thanks.


Detailed steps below.

inputs: (The lower one is the source and the upper one is the target)
![tube1](https://user-images.githubusercontent.com/10392640/149573276-187a1511-15a3-443f-941f-0cc8b3cdf31c.png)

registration with rigid transformation (ICP)
![tube2](https://user-images.githubusercontent.com/10392640/149573391-ec07d50e-32e9-442f-915a-504069f4e0a3.png)

registration with bcpd
./bcpd -A -DB,5000,0.08 -L100 -x source.txt -y target.txt -J300 -K70 -p -r1 -L100 -c1e-6 -g.10 -n1000 -b1.2 -l50 -ux

![tube3](https://user-images.githubusercontent.com/10392640/149573563-9bd1b7a0-efb3-4105-b177-32e32935a9fa.png)

Comparison between ICP and BCPD result
![tube4](https://user-images.githubusercontent.com/10392640/149573747-a7e86ce0-5e3e-4023-8c35-5c663658f1c7.png)

The BCPD command outputs:
 BCPD version 0.85 (2020/10/19). OpenMP: Turned on.

```
  Input Data:
    Point set 1 (target): [./source.txt]
    Point set 2 (source): [./target.txt]
    Size of point set 1:  [857509, 3]
    Size of point set 2:  [846887, 3]

  Parameters: 
    omega   =  0.00
    lambda  =  50.00  --> the expected drift length = 0.245
    gamma   =  0.10
    kappa   =  inf

  Kernel:
    [Gaussian] with beta = 1.20

  Acceleration: 
    Downsampling:
      Target -->  5000 [voxel grid: r=0.080]
      Source -->  5000 [voxel grid: r=0.080]
    Fast G:  K = 70
    Fast P:  
      Nystrom: J = 300
      KD tree: r = min(0.15,7.0*sigma) if sigma < 0.20
    Fast Interpolation:  L = 100
    Rand seed: 1

  Convergence: 
    tolerance   =  1.0e-06
    max #loops  =  1000
    min #loops  =  30

  Output: 
    [tube_registered_*.txt]; * = y

  Normalization: [using X]
    Bounding boxes that cover point sets:
    Before:
      Target: x=[-0.16,7.08], y=[-1.22,0.20], z=[-2.70,3.00]
      Source: x=[-0.14,6.91], y=[-1.05,0.21], z=[-2.66,3.02]
    After:
      Target: x=[-1.91,2.06], y=[-0.44,0.34], z=[-1.56,1.56]
      Source: x=[-1.90,1.97], y=[-0.35,0.34], z=[-1.54,1.58]

  Downsampling ... done. 

  VB optimization: -|  -  |-
    loop   =  87
    Np     =  5000.000000
    sigma  =  0.014346
    diff   =  0.000001
    conv   =  0.000001
    acc.P  =  KDtree 

  Interpolating ... done. 

  Computing Time:
    VB Optimization: 7.32 sec (real) / 113.76 sec (cpu)
    Downsampling:    0.099 sec (real) / 0.099 sec (cpu)
    Interpolation:   9.273 sec (real) / 15.940 sec (cpu)
    File reading:    1.417 sec
    File writing:    0.008 sec
```

**Comment by ohirose** [comment]
Thank you for your interesting report. Is it possible to upload the input point clouds?
If they cannot be public, please email me: ![CodeCogsEqn](https://user-images.githubusercontent.com/7005476/149592681-13d246e6-8a5e-4f77-8fe2-ec0d445c0da1.png)

**Comment by szx0112** [comment]
@ohirose  Thanks for the reply. Point clouds are sent through email.

**Comment by szx0112** [comment]
The problem was solved with the help of @ohirose. The source and target models can now be aligned.
