### ISSUE TITLE
Error using *

### ISSUE THREAD

**Issue by sandwich25** [ohirose/bcpd#2]
Hi, I keep getting the error as shown in the screenshot below. Does it have something to do with my data files? I have attached the data files for your reference.
<img width="524" alt="error" src="https://user-images.githubusercontent.com/69758962/92844682-7743f400-f429-11ea-9b21-24bf99c6ce81.PNG">
[complex-x.txt](https://github.com/ohirose/bcpd/files/5205557/complex-x.txt)
[complex-y.txt](https://github.com/ohirose/bcpd/files/5205558/complex-y.txt)

**Comment by ohirose** [comment]
Hi, sandwich25

I checked your data. After converting them into tab-delimited files, I confirmed that BCPD successfully registered your data.

The BCPD's file-read function is not so smart, and therefore, it seems that BCPD failed to read your input files. Your files are space-delimited, and BCPD cannot read space-delimited files. First of all, please convert your files into tab-delimited files using Matlab, R, or GNU Octave, for example. Also, please do not insert any tab symbols after the last column.

In case of Matlab, the following command convert your files into tab-delimited files:

  x=load('complex-x.txt'); dlmwrite('X.txt',x,'\t');
  y=load('complex-y.txt'); dlmwrite('Y.txt',y,'\t');

After the file conversion, please run BCPD using the following command:

  bcpd -x X.txt -y Y.txt -l1e9 -w0.1 -J300 -K70 -p -e0.3 -f0.3 -g3 -DB,5000,0.08 -sY

Thanks.

**Comment by ohirose** [comment]
Here's the result:
[
<img width="1351" alt="Screen Shot 2020-09-11 at 2 00 23 PM" src="https://user-images.githubusercontent.com/7005476/92863722-3a7ef980-f437-11ea-9f90-34af58fae134.png">
](url)

**Comment by sandwich25** [comment]
Thank you very much!
