### ISSUE TITLE
I cannot install it on ubuntu 18.04

### ISSUE THREAD

**Issue by PrideDream** [ohirose/bcpd#20]
**Expected behavior**
Intsall BCPD on Ubuntu 18.04

When run the following command
`make OPT=-DUSE_OPENMP ENV=LINUX`

**Error**
`gcc -O3 -fopenmp -DUSE_OPENMP -g -Wall register/*.c base/*.c -o bcpd -lm -llapack
In file included from base/kdtree.c:24:0:
base/kdtree.c: In function ‘nnsearch’:
base/kdtree.c:151:30: warning: array subscript is below array bounds [-Warray-bounds]
   while(q){assert(q>=0||(q&&S[q-1]>=0)); n=S[--q];`

**Additiona context**
I am sure LAPACK is installed

I am looking forward to your help.

**Comment by ohirose** [comment]
It seems to be compiler warnings instead of compiler errors. Didn't you see the binary 'bcpd' generated after the compilation?

**Comment by PrideDream** [comment]
The error is
` -bash: ./bcpd: 没有那个文件或目录`
The English meaning is : The file was not found
It does not appear to have been successfully installed.

My computer cpu :Intel(R) Xeon(R) Gold 5218 CPU ;  gpu: NVIDIA TITAN RTX  
Do these hardware make a difference ?

**Comment by ohirose** [comment]
Did you write all errors (and all output) from the compiler?

**Comment by PrideDream** [comment]
I posted the question on my github page: https://github.com/PrideDream/hello_world/blob/master/bug.md

**Comment by PrideDream** [comment]
I uploaded the error to my github :  https://github.com/PrideDream/hello_world/blob/master/bug.md

**Comment by ohirose** [comment]
First of all, it seems that you succeeded in the compilation. 
Your execution failed because of a memory allocation error.
Please attach the option `-A -DB,5000,0.08 -L100`.
Also, I would be most grateful if you could read README carefully.

**Comment by PrideDream** [comment]
I run the code successfully. Thank you very much for your help.
