### ISSUE TITLE
Can bcpd register colored point cloud ?

### ISSUE THREAD

**Issue by PrideDream** [ohirose/bcpd#21]
Hello ohirose,
Let me write it at the front，**Congratulations on Posting a journal in TPAMI**.

****
**Expected behavior**
What I want to is use bcpd to register **colored** point cloud: matlab_miccai_color_x.txt and matlab_miccai_color_y.txt
> -x [file]: The target shape represented as a matrix of size N x D.
-y [file]: The source shape represented as a matrix of size M x D.

Referring to the README above, I added rgb color information directly after the coordinates.
The meaning of each column in the txt is x coordinate, y coordinate,z coordinate, r, g, b.
rgb range from 0 to 1.
[matlab_miccai_color_x.txt](https://github.com/ohirose/bcpd/files/9783447/matlab_miccai_color_x.txt)
[matlab_miccai_color_y.txt](https://github.com/ohirose/bcpd/files/9783448/matlab_miccai_color_y.txt)

The command is :
`win/bcpd.exe -xmatlab_miccai_x.txt -ymatlab_miccai_y.txt -w0.0 -b2.0 -l3.464 -g10 -J300 -K70 -p -e0.15 -f0.2 -c1e-3 -n500 -h -r1  -sY`

The output seems to be wrong and no output file is generated:
`  Output: 
    [output_*.txt]; * = y
  loop=001  acc.P=[Nystrom]  sigma=0.999994          
  loop=002  acc.P=[Nystrom]  sigma=-1.#IND00  diff=1.#QNAN0`

**Additional information**
By the way, I have **successfully** implemented the registration of point clouds without color.
The data is matlab_miccai_x.txt and matlab_miccai_y.txt.
[matlab_miccai_x.txt](https://github.com/ohirose/bcpd/files/9783449/matlab_miccai_x.txt)
[matlab_miccai_y.txt](https://github.com/ohirose/bcpd/files/9783450/matlab_miccai_y.txt)
The command is following:
`win/bcpd.exe -xmatlab_miccai_x.txt -ymatlab_miccai_y.txt -w0.0 -b2.0 -l3.464 -g10 -J300 -K70 -p -e0.15 -f0.2 -c1e-3 -n500 -h -r1  -sY`

Does bcpd support colored point cloud？
If it does, what should I do？

**Comment by ohirose** [comment]
Currently, the registration performance is unknown for more than three-dimensional data. Please apply BCPD to 3D (or 2D) point sets.
