### ISSUE TITLE
About the downsampling process

### ISSUE THREAD

**Issue by wzm2256** [ohirose/bcpd#23]
Hi, I have a question about the downsampling process.

I see the code accept two parameters for downsampling: `-D [char,int,real]`, where the second parameter is the number of selected point, and the third parameter is used for voxel or ball sampling. My question is that how does the code control the number of sampled points while using voxel or ball sampling?  

Does the code first downsample the points using voxel or ball sampling, then output a fraction of points from the results?

Thanks for your time.

**Comment by ohirose** [comment]
Very simple: 
Voxel-grid (or ball) resampling resamples the desired number of points from a categorical distribution; each category probability is inversely proportional to the number of points inside the corresponding voxel (or ball). 

> Does the code first downsample the points using voxel or ball sampling, then output a fraction of points from the results?

No. The procedure is as follows:
1. Compute category probabilities. 
2. Draw the desired number of samples (points) from the categorical distribution.

**Comment by wzm2256** [comment]
Thanks a lot! That makes sense. 

This is slightly different from the deterministic voxel sampling I know, which is to divide all points into voxels, and keep one points in each voxel. This deterministicc voxel sampling can generate points more uniformly as there is no risk of samping all points in only one voxel, but there is no way to control the number of sampled points. Your probablistic sampling method can indeed sample a given number of points uniformly, but I guess it is not very uniform when the number of sampled points are small, and some special treatments may be needed to handle the excessively small voxels, where each voxel contain at most one point, thus this sampling strategy becomes the uniform sampling of points.

Anyway, this is really interesting, and thanks for you fast reply!
