### ISSUE TITLE
关于大数据量的三维模型，导致程序直接退出

### ISSUE THREAD

**Issue by saivian1** [ohirose/bcpd#26]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ohirose** [comment]
More than 20M points? If it isn’t, you didn't activate any acceleration technique; bcpd failed because of the memory allocation error. Please add the option -A; read [here](https://github.com/ohirose/bcpd#acceleration) carefully.

**Comment by saivian1** [comment]
89981kb
