### ISSUE TITLE
About big data 3D model, program flash back problem

### ISSUE THREAD

**Issue by saivian1** [ohirose/bcpd#27]
**Describe the bug**
    My data are two point cloud models with sizes of 89MB. A and D have been added according to your reply just now.
But problems remain. Thank you for your reply

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by saivian1** [comment]
My data are two point cloud models with sizes of 89MB. A and D have been added according to your reply just now.
But problems remain. Thank you for your reply

**Comment by ohirose** [comment]
How many points does each point set have? Please attach the link for downloading your data.
Also, attach the command you specified.

**Comment by saivian1** [comment]
My data is provided by the hospital and can be found in the attachment.
Each point set has 516,412 points

the command you specified.：
omg = '0.0'
bet = '2.0'
lmd = '50'
gma = '10'
K = '70'
J = '300'
c = '1e-6'
A = ''
n = liter_number
L = '100'
nrm = 'e'
d = '7'
e = '0.15'
f = '0.2'
##dwn进行下采样时的点数
dwn = 'B,' + dwnpoint + ',0.08'
prm1 = "-w%s -b%s -l%s -g%s" % (omg, bet, lmd, gma)
prm2 = "-J%s -K%s -p -d%s -e%s -f%s -L%s -u%s -D%s" % (J, K, d, e, f, L, nrm, dwn)
prm3 = "-c%s -n%s -h -r1" % (c, n)
source = "%s -x%s -y%s %s %s %s -sY" % (exepath, x, y, prm1, prm2, prm3)
print(source)
os.system(source)



1446174581
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ohirose/bcpd"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月3日(星期五) 下午5:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ohirose/bcpd] About big data 3D model, program flash back problem (Issue #27)





 
How many points does each point set have? Please attach the link for downloading your data.
 Also, attach the command you specified.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

average.stl (87.87M, 2023年03月05日 17:08 到期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=78303138a038e1cc4def036e123651190a00555c0455525515005059001b570f01011c595707571b0a08540b510f5a050952530e343d63574e55435953534d454c5c3105&t=exs_ftn_download&code=801846c6

**Comment by ohirose** [comment]
Please convert your STL file to a text file. The endian problem matters for binary data

**Comment by saivian1** [comment]
stl has been converted to text data


1446174581
***@***.***


stl has been converted to text data
&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "ohirose/bcpd"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月3日(星期五) 下午5:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ohirose/bcpd] About big data 3D model, program flash back problem (Issue #27)





 
Please convert your STL file to a text file. The endian problem matters for binary data

**Comment by ohirose** [comment]
I am sorry, I can't find a new link in your reply. Please send a new link for downloading the text file.

**Comment by saivian1** [comment]
1446174581
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ohirose/bcpd"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月3日(星期五) 晚上6:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ohirose/bcpd] About big data 3D model, program flash back problem (Issue #27)





 
I am sorry, I can't find a new link in your reply. Please send a new link for downloading the text file.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

x.txt (10.76M, 无限期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=583032383cf7619d17ef006e1e34004d525157085d5006004f52535c5d19060051071f005b04054f5008505d0e50565b0705570e3831321a4c444a4c3809&t=exs_ftn_download&code=b028842b

**Comment by ohirose** [comment]
Please convert the STL file format into a tab-separated file that BCPD can read. Did you read an input file section in README?

**Comment by saivian1** [comment]
Here's how my code saves the point cloud data. Is already TAB interval.
np.savetxt(respath_x, target, fmt='%.2f', delimiter='\t')
np.savetxt(respath_y, source, fmt='%.2f', delimiter='\t')
&nbsp;


1446174581
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Osamu ***@***.***&gt;; 
发送时间: 2023年2月3日(星期五) 晚上7:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ohirose/bcpd] About big data 3D model, program flash back problem (Issue #27)





 
Please convert the STL file format into a tab-separated file that BCPD can read. Did you read an input file section in README?

**Comment by ohirose** [comment]
Please send me a download link once again. Your link didn't work now

**Comment by saivian1** [comment]
1446174581
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ohirose/bcpd"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月3日(星期五) 晚上7:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ohirose/bcpd] About big data 3D model, program flash back problem (Issue #27)





 
Please send me a download link once again. Your link didn't work now
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

x.txt (10.76M, 无限期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=596361313df037cb16bc53671f33561b515403060f0005074e5a57575a1e50015a014c095a5601195a5752080e0a5456060752073936644c4d171945390e&t=exs_ftn_download&code=cca193d4

**Comment by ohirose** [comment]
BCPD correctly worked in my environment. Here's the result:
<img width="577" alt="Screen Shot 2023-02-03 at 12 31 14" src="https://user-images.githubusercontent.com/7005476/216593183-1754423b-49e6-4557-a510-277fda3b28aa.png">
Check your script once again

**Comment by ohirose** [comment]
How about executing BCPD in your terminal? Use the following command for example:
`./bcpd -x x.txt -y x.txt -A -DB,1000,.01`

**Comment by saivian1** [comment]
Thank you so much. Thank you so much
&nbsp;


1446174581
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Osamu ***@***.***&gt;; 
发送时间: 2023年2月3日(星期五) 晚上7:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ohirose/bcpd] About big data 3D model, program flash back problem (Issue #27)





 
How about executing BCPD in your terminal? Use the following command for example:
 ./bcpd -x x.txt -y x.txt -A -DB,1000,.01

**Comment by saivian1** [comment]
Thank you so much. Thank you so much

**Comment by saivian1** [comment]
bcpd/win/bcpd.exe -x x.txt -y y.txt -w0.0 -b2.0 -l50 -g10 -J300 -K70 -p -d7 -e0.15 -f0.2 -L100 -ue -DB,516412,0.08 -c1e-6 -n10000 -h -r1 -sY -A -DB,1000,.01 -G geodesic,0.2,8,0.15
The command -G geodesic,0.2,8,0.15 was added, which means GBCPD of geodesic is enabled. Here is the effect. It doesn't look much different from BCPD. Is there something wrong with the way I open it?





1446174581
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ohirose/bcpd"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月3日(星期五) 晚上7:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ohirose/bcpd] About big data 3D model, program flash back problem (Issue #27)





 
How about executing BCPD in your terminal? Use the following command for example:
 ./bcpd -x x.txt -y x.txt -A -DB,1000,.01

**Comment by ohirose** [comment]
I can't imagine because you didn't provide `y.txt`. First, read my manuscripts carefully. And be careful not to waste our time. Please. Thanks.

**Comment by saivian1** [comment]
Thank you very much&nbsp;


1446174581
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Osamu ***@***.***&gt;; 
发送时间: 2023年2月3日(星期五) 晚上8:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ohirose/bcpd] About big data 3D model, program flash back problem (Issue #27)





 
I can't imagine because you didn't provide y.txt. First, read my manuscripts carefully. And be careful not to waste our time. Please. Thanks.
