### ISSUE TITLE
Question regarding kappa and non-rigid deformation

### ISSUE THREAD

**Issue by intrinsicD** [ohirose/bcpd#3]
Hello,

I implemented bcpd my self using eigen and I have run into some issues regarding your algorithm. 

Could you elaborate a bit about the role of the kappa parameter? You seem to set it to infinity in all of your examples but you never specified how you compute the digamma function. I use the formula from Wikipedia, up to a precision of O(14). It seems to work but when kappa is large the recursion takes a long time to compute the value.

Additionally it seems that before registration one has to fix the parameter beta and if beta is too large the local deformation can't contain fine deformations. If beta is to low I observed an oscillating problem and the deformations become unstable. It also seems that the rigid transformation parameters can only be determined up to the point when the local deformations capture the residual completely. 

Did you observe similar problems?

I currently do not use any acceleration regarding the computation of P and Sigma, so maybe that is the root of the problem?

Best regards and thank you for this nice registration algorithm 😊,
Alex

**Comment by ohirose** [comment]
Hi, Alex

Thank you for your interest in BCPD!

>> Could you elaborate a bit about the role of the kappa parameter? 

The parameter kappa removes the constraint on the mixing coefficients being equivalent.

>> You seem to set it to infinity in all of your examples but you never specified how you compute the digamma function. 

If we set kappa to infinity, the equivalence of mixing coefficients is mathematically guaranteed (Please check the Dirichlet distribution in Wikipedia). Therefore, BCPD skips the computation of the digamma function if kappa is set to infinity. 

>> I use the formula from Wikipedia, up to a precision of O(14). It seems to work but when kappa is large the recursion takes a long time to compute the value.

For non-infinity kappa, I use the C code written by R. Neal, which does not seem to yield such a problem as far as I tried. Please check the following link:
http://places.csail.mit.edu/deepscene/small-projects/Max-value-Entropy-Search/GPstuff-4.4/dist/winCsource/digamma1.c

>> Additionally it seems that before registration one has to fix the parameter beta and if beta is too large the local deformation can't contain fine deformations. If beta is to low I observed an oscillating problem and the deformations become unstable. It also seems that the rigid transformation parameters can only be determined up to the point when the local deformations capture the residual completely.

Please provide more information about the oscillating problem.  I would appreciate it if you uploaded example data that reproduce these events in your next comment. 

Thanks.

**Comment by intrinsicD** [comment]
Thank you for pointing me to the C-code. I have it running now, and i am trying to extend my implementation to BCPD++ :)

**Comment by KernelA** [comment]
Hi, @ohirose.

Why kappa is infinity by default as pointed in the README, but in C code it equals to ZERO?

https://github.com/ohirose/bcpd/blob/76b1b3035feeb593be558b800c2e25b9fca6dc37/register/main.c#L175

**Comment by ohirose** [comment]
Hi, Mr. Alexander Kryuchkov

Thank you for your interest in BCPD! ''kappa <=ZERO'' in my code means that kappa is treated as infinity. Please see line 233 in bcpd.c, which means that if kappa equals (or is very close) to ZERO, kappa won't be updated, and it remains to be 1/M (see also line 134 in bcpd.c). If you have a question, please email me instead of raising an issue.

Regards,
Osamu Hirose

**Comment by KernelA** [comment]
Thank you for answer

**Comment by ohirose** [comment]
I edited the previous answer. Please check the difference by clicking the triangle near the ''edited" mark.
