### ISSUE TITLE
Question Regarding Error Measurement

### ISSUE THREAD

**Issue by sandwich25** [ohirose/bcpd#4]
Hi,
In the list of variables from MatLab, I noticed there is a variable called "a". Is it the error measurement? If yes, is it measured as root mean squared error?
![what is a](https://user-images.githubusercontent.com/69758962/93438241-5c352080-f910-11ea-940c-6cf7bae17311.jpg)

**Comment by ohirose** [comment]
Hi, please check optpath3.m. The variable "a" is used for visualization only.

**Comment by sandwich25** [comment]
sorry, but what should I be looking for in optpath3.m?

**Comment by ohirose** [comment]
demo/optpath3.m
