### ISSUE TITLE
Plans to upload source code?

### ISSUE THREAD

**Issue by asdwer20** [ohirose/bcpd#7]
Hi, I was wondering if you had any future plans on uploading the uncompiled source code for the program? I was fascinated by the performance of your program and would love to study it further in depth. Thanks!

**Comment by BrentFoster** [comment]
I was wondering about the source code as well. Also is there a plan to add a license (such as the MIT license) to the code?

**Comment by ohirose** [comment]
I am sorry for being late for the reply. I uploaded the source code. Please check it if you are still interested.

**Comment by BrentFoster** [comment]
Thanks very much!! I will look through it now, and it should be very helpful.

**Comment by asdwer20** [comment]
Awesome! Thank you!
