### ISSUE TITLE
Derivation in supplementary materials for q_1

### ISSUE THREAD

**Issue by intrinsicD** [ohirose/bcpd#8]
Hello ohirose,

I'm preparing a lecture on CPD and I'm stuck at the derivation for the Dirichlet distribution for alpha. I managed to get the correct equation for your term of ln q_1(v,alpha). It is exactly the same as you have in your supplementary materials except I'm missing the 1/2 factor in the last double sum.

First can you please explain where it comes from, and further explain where it vanishes to when you combine the alpha terms from the prior and the two-component mixture?

Thank you in advance.
Best Regards, 
Alex

**Comment by ohirose** [comment]
Hi Alex,

Thank you for your interest in BCPD! You are correct. Please remove the 1/2 factor in the last double sum.

Best regards,
Osamu

**Comment by intrinsicD** [comment]
Hello Osamu,

Thank you for your reply. I have a followup question, regarding the connection of the Expected value of ln alpha and the digamma function. You skipped that in your paper and the supplementary materials. Can you explain how you arrive at <\alpha_{mn}>=exp(\digamma(\kappa +\nu)-\digamma(\kappa M+\hat{N})) or point me towards the used literature? I saw on Wikipedia that the Expected Value of a Dirichlet distribution contains the digamma function, but i fail to see the concrete connection. Sorry for all the trouble ;)
Best regards and thank you in advance,
Alex

**Comment by ohirose** [comment]
For example, see https://stats.stackexchange.com/questions/483312/how-to-derive-the-expectation-of-ln-mu-j-in-dirichlet-distribution

**Comment by intrinsicD** [comment]
Thank you very much for the link! I could successfully derive the factor q_1 and q_2. But i'm stuck at the last factor's argument that we can compute the lower bound of q_3 as the expectation over q_1q_2 of the ln p(x,y\rho,\sigma^2). I can see the first part but if i plug in the delta function into the lower bound i get for the entropy part that it is minus infinity. How did you handle that? Did you set it to constant because it is always minus infinity? What is the correct argument here, i can't see it :(

Best regards,
Alex

**Comment by ohirose** [comment]
Please ask experts in this field, e.g., Zoubin Ghahramani or Tom Minka, who said the statement is correct ([paper](http://mlg.eng.cam.ac.uk/zoubin/papers/valencia02.pdf) and [forum](https://stats.stackexchange.com/questions/105661/relation-between-variational-bayes-and-em)). Probably, they have a better understanding than mine.

**Comment by intrinsicD** [comment]
Hello Osamu,
we figured out how the argument works. If you assume q_3 to be a delta distribution and model it as the limit of a gaussian with sigma->0, then you can just plug it into the lower bound. Evaluating the integral and afterwards the limit, the negative entropy term vanishes and you are left with the formula you provide in the supplementary material.

**Comment by ANG0-0GNA** [comment]
Hi, Osamu and Alex @intrinsicD, 
I'm still confused on the update of q_3. Could you help me understand this step? The task in q_3
is to maximize the lower bound. But after writing L(q_1*q_2*q_3), there is a term ln(q_3) besides the the expectation over q_1q_2 E[ln p(x,y,\theta)] as shown in the picture. Is it right? how to understand this? Or I just regard this part as an EM algorithm to find the Q function in E-step.
![update of q _3](https://user-images.githubusercontent.com/28749941/108840441-52c38900-7611-11eb-8b6b-df0814a0c751.png)



> Hello Osamu,
> we figured out how the argument works. If you assume q_3 to be a delta distribution and model it as the limit of a gaussian with sigma->0, then you can just plug it into the lower bound. Evaluating the integral and afterwards the limit, the negative entropy term vanishes and you are left with the formula you provide in the supplementary material.
> 
> Thank you for your input and the links to the relevant material!

**Comment by ohirose** [comment]
You can't drop q3 from Eq. 17 because q3 is unknown. Instead, you will get the following equation:
![image](https://user-images.githubusercontent.com/7005476/108859822-f40e0780-7630-11eb-9596-17a73354aec5.png)
Then, you can drop the entropy term, i.e., the second term, as discussed.
Or, it's possible to avoid using the Dirac delta. As you suggested, you can combine VB and EM as follows:

1. Update q1 and q2 with VB (= EM's E-step), 
2. Update ![image](https://user-images.githubusercontent.com/7005476/108861465-97135100-7632-11eb-9bd9-6bf933521219.png)  at EM's M-step. 

This procedure does not change the resulting algorithm.

**Comment by ANG0-0GNA** [comment]
Thank you for your reply! I rewrite the process from eq. 17 to 18 in the last picture.
And I want to make sure the expectation over q_1 q_2 or q(123)  in the following picture.
![expectation](https://user-images.githubusercontent.com/28749941/108938541-382df600-768b-11eb-8fe2-c17a2eda9776.jpg)

Here is the process from eq. 17 to 18:
![17 to 18_2](https://user-images.githubusercontent.com/28749941/108938546-39f7b980-768b-11eb-8df4-bf05a9c53a28.jpg)

Best regards,
Ang

**Comment by ohirose** [comment]
q(123). For more information, see Exercise 10.5 in [Bishop's PRML](http://users.isr.ist.utl.pt/~wurmd/Livros/school/Bishop%20-%20Pattern%20Recognition%20And%20Machine%20Learning%20-%20Springer%20%202006.pdf), for example. Its solution is available in [book's supporting material](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/05/prml-web-sol-2009-09-08.pdf).

**Comment by ANG0-0GNA** [comment]
Thank you for your reply! I got it!
